export default [
  {
    title: "MENU",
    permissions: [],
    permissionsStrict: true,
  },
  {
    title: "Dashboards",
    url: "/dashboard",
    icon: "bx-home-circle",
    hasArrow: false,
    badge: "info",
    badgeText: "04",
    permissions: [],
    permissionsStrict: true,
    children: [],
  },
  {
    title: "MANTENIMIENTO",
    permissions: [],
    permissionsStrict: true,
  },
  {
    title: "Empresas",
    url: "/company",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["3_consultar"],
    permissionsStrict: true,
  },
  {
    title: "Roles",
    url: "/roles",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["6_consultar"],
    permissionsStrict: true,
  },
  {
    title: "Empleados",
    url: "/employee",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["9_consult"],
    permissionsStrict: true,
  },
  {
    title: "Usuario",
    url: "/user",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["9_consultar"],
    permissionsStrict: true,
  },
  {
    title: "Producto",
    url: "/product",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["1_consultar"],
    permissionsStrict: true,
  },
  {
    title: "Tipo",
    url: "/type",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["8_consultar"],
    permissionsStrict: true,
  },
  {
    title: "Marca",
    url: "/brand",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["4_consultar"],
    permissionsStrict: true,
  },
  {
    title: "Materiales",
    url: "/material",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["5_consultar"],
    permissionsStrict: true,
  },
  {
    title: "Productos en almacen",
    url: "/warehouse",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["10_consultar"],
    permissionsStrict: true,
  },
  {
    title: "voz",
    url: "/voz",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["11_consultar"],
    permissionsStrict: true,
  },
  {
    title: "Orden de compra",
    url: "/#",
    icon: "bx-home-circle",
    hasArrow: true,
    badge: null,
    badgeText: null,
    permissions: ["12_consultar", "12_insertar"],
    permissionsStrict: false,
    children: [
      {
        title: "Listar",
        url: "/purchase-order",
        permissions: ["12_consultar"],
        permissionsStrict: true,
      },
      {
        title: "Crear",
        url: "/purchase-order-create",
        permissions: ["12_insertar"],
        permissionsStrict: true,
      },
    ],
  },
  {
    title: "Orden de salida",
    url: "/#",
    icon: "bx-home-circle",
    hasArrow: true,
    badge: null,
    badgeText: null,
    permissions: ["12_consultar", "12_insertar"],
    permissionsStrict: false,
    children: [
      {
        title: "Listar",
        url: "/exit-order",
        permissions: ["12_consultar"],
        permissionsStrict: true,
      },
      {
        title: "Crear",
        url: "/exit-order-create",
        permissions: ["12_insertar"],
        permissionsStrict: true,
      },
    ],
  },
]
