export default [
  {
    title: "MENU",
    permissions: [],
    permissionsStrict: true,
  },
  {
    title: "Dashboards",
    url: "/dashboard",
    icon: "bx-home-circle",
    hasArrow: false,
    badge: "info",
    badgeText: "04",
    permissions: [],
    permissionsStrict: true,
    children: [],
  },
  {
    title: "Marcas",
    url: "/brand",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["1_consult"],
    permissionsStrict: true,
  },
  {
    title: "Productos",
    url: "/product",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["2_consult"],
    permissionsStrict: true,
  },
  {
    title: "Almacenes",
    url: "/store",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["3_consult"],
    permissionsStrict: true,
  },
  {
    title: "Tipos",
    url: "/type",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["4_consult"],
    permissionsStrict: true,
  },
  {
    title: "Modelo",
    url: "/category",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["5_consult"],
    permissionsStrict: true,
  },
  {
    title: "Reporte",
    url: "/#",
    icon: "bx-home-circle",
    hasArrow: true,
    badge: null,
    badgeText: null,
    permissions: ["6_consult"],
    permissionsStrict: false,
    children: [
      {
        title: "Reporte por fechas",
        url: "/sales/report-date",
        permissions: ["6_consult"],
        permissionsStrict: true,
      },
    ],
  },
  {
    title: "Sedes",
    url: "/head-quarter",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["7_consult"],
    permissionsStrict: true,
  },
  {
    title: "Ventas y Proformas",
    url: "/#",
    icon: "bx-home-circle",
    hasArrow: true,
    badge: null,
    badgeText: null,
    permissions: ["8_consult"],
    permissionsStrict: false,
    children: [
      {
        title: "Ventas",
        url: "/sales",
        permissions: ["8_consult"],
        permissionsStrict: true,
      },
      {
        title: "Crear venta",
        url: "/sales/create",
        permissions: ["8_consult"],
        permissionsStrict: true,
      },
    ],
  },
  {
    title: "Empleado",
    url: "/employee",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["9_consult"],
    permissionsStrict: true,
  },
  {
    title: "Usuarios",
    url: "/user",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["10_consult"],
    permissionsStrict: true,
  },
  {
    title: "Roles",
    url: "/roles",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["11_consult"],
    permissionsStrict: true,
  },
  // {
  //   title: "Proveedor",
  //   url: "/",
  //   icon: "bx-calendar",
  //   hasArrow: false,
  //   badge: null,
  //   badgeText: null,
  //   children: [],
  //   permissions: ["12_consult"],
  //   permissionsStrict: true,
  // },
  {
    title: "Calidad",
    url: "/material",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["13_consult"],
    permissionsStrict: true,
  },
  {
    title: "Empresa",
    url: "/company",
    icon: "bx-calendar",
    hasArrow: false,
    badge: null,
    badgeText: null,
    children: [],
    permissions: ["14_consult"],
    permissionsStrict: true,
  },
  {
    title: "Provedores",
    url: "/#",
    icon: "bx-home-circle",
    hasArrow: true,
    badge: null,
    badgeText: null,
    permissions: ["12_consult"],
    permissionsStrict: false,
    children: [
      {
        title: "Provedor",
        url: "/providers",
        permissions: ["12_consult"],
        permissionsStrict: true,
      },
      {
        title: "Contacto de proveedor",
        url: "/supplier-contact",
        permissions: ["12_consult"],
        permissionsStrict: true,
      },
    ],
  },
]
